app:
  build: ./app
  command: uwsgi --http :8000 --wsgi-file /app/main.py --master
  env_file: .env
  expose:
    - "8000"
  links:
    - memcached
    - redis
  restart: always

nginx:
  build: ./conf/nginx
  links:
    - app
  ports:
    - "80:80"
  restart: always

memcached:
  image: memcached
  restart: always
  expose:
    - "11211"

redis:
  image: redis

celery:
  build: ./app
  command: celery worker --app=app.main
  env_file: .env
  environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
  links:
    - memcached
    - redis
  restart: always
